### ISSUE TITLE
Hyprland

### ISSUE THREAD

**Issue by Malix-Labs** [Drakulix/cosmic-ext-extra-sessions#6]
Hello Drakulix!
It would be nice to implement hyprland :)
i could try to make a full pr this weekend, but couldn't finish the tests before the next week

**Comment by Drakulix** [comment]
See README.

**Comment by Malix-Labs** [comment]
:(

**Comment by mattkang** [comment]
@Drakulix totally your choice as to what you want to support. Can I just ask what the rationale is behind this decision?

**Comment by Drakulix** [comment]
> @Drakulix totally your choice as to what you want to support. Can I just ask what the rationale is behind this decision?

Because I have no interest in engaging with the hyprland community in any capacity.
